version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: upiiz_db
    environment:
      POSTGRES_DB: upiiz_platform
      POSTGRES_USER: upiiz
      POSTGRES_PASSWORD: upiizpass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U upiiz -d upiiz_platform"]
      interval: 5s
      timeout: 3s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: upiiz_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@upiiz.mx
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8081:80"
    depends_on:
      - db

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: upiiz_mailhog
    ports:
      - "8025:8025"   # UI MailHog (web)
      - "1025:1025"   # SMTP

  backend:
    build:
      context: ./backend
    container_name: upiiz_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/upiiz_platform
      SPRING_DATASOURCE_USERNAME: upiiz
      SPRING_DATASOURCE_PASSWORD: upiizpass
      # Si tu app manda correos por SMTP, MailHog queda as√≠:
      SPRING_MAIL_HOST: mailhog
      SPRING_MAIL_PORT: 1025
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: upiiz_frontend
    ports:
      - "4200:3030"
    restart: always
    depends_on:
      - backend
    environment:
      API_BASE_URL: http://backend:8080

volumes:
  db_data:
